import subprocess, shutil
import time as t
import pyautogui as pg
import sys


def minimize_all_windows_cross_platform(prefer="show_desktop"):
    """
    Attempts to show desktop/minimize windows on Windows, macOS and Linux.
    prefer: "show_desktop" (Win+D/F11/Super+D) or "minimize" (Win+M on Windows).
    """
    t.sleep(0.2)
    try:
        if sys.platform == "win32":
            # Win: Win+D (toggle) or Win+M (minimize only)
            if prefer == "minimize":
                pg.hotkey("winleft", "m")
            else:
                pg.hotkey("winleft", "d")

        elif sys.platform == "darwin":
            # macOS: try "Show Desktop" (usually bound to F11)
            # Permissions required: System Preferences → Security & Privacy → Accessibility (Terminal/Python)
            try:
                subprocess.run(
                    [
                        "osascript",
                        "-e",
                        'tell application "System Events" to key code 103',
                    ],
                    check=True,
                )
            except Exception:
                # Fallback: "Hide Others" (Cmd+Opt+H) - not quite "show desktop", but it clears up the screen noticeably.
                subprocess.run(
                    [
                        "osascript",
                        "-e",
                        'tell application "System Events" to keystroke "h" using {command down, option down}',
                    ],
                    check=False,
                )

        else:
            # Linux/*nix: many DEs (GNOME/KDE) use Super+D.
            ok = False
            try:
                pg.hotkey("winleft", "d")
                ok = True
            except Exception:
                pass
            # If there is xdotool (X11), let's pull it too - it's often more reliable.
            if not ok and shutil.which("xdotool"):
                try:
                    subprocess.run(["xdotool", "key", "Super+d"], check=False)
                    ok = True
                except Exception:
                    pass

    except Exception:
        pass


# this file was generated by chatGPT
